"""empty message

Revision ID: 2639619b9017
Revises: e7450db26977
Create Date: 2022-04-21 23:52:37.107349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2639619b9017'
down_revision = 'e7450db26977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_people', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uid_people'], ['people.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_people')
    # ### end Alembic commands ###
